### ISSUE TITLE
GP4 generated project is not patch

### ISSUE THREAD

**Issue by bubufofo** [maxton/LibOrbisPkg#63] opened 2020-07-22 17:38 UTC
pointing pkg editor and generating gp4 project
![image](https://user-images.githubusercontent.com/57014830/88209269-c0aa6b00-cc52-11ea-8100-fe956293e56e.png)

generated gp4 is app not patch
![image](https://user-images.githubusercontent.com/57014830/88209325-d881ef00-cc52-11ea-9a0b-333e6db85f44.png)

**Comment by maxton** [comment] 2020-07-22 19:38
dupe of #62 -- see response there

**Closed by maxton** 2020-07-22 19:38 UTC
Labels: duplicate
