### ISSUE TITLE
Playgo Chunk hash file was not allocated enough space.

### ISSUE THREAD

**Issue by nkrapivin** [maxton/LibOrbisPkg#56] opened 2020-04-13 06:37 UTC
When I try to build a package it says.
```
Error: System.Exception: Playgo Chunk hash file was not allocated enough space. Report this as a bug
   в LibOrbisPkg.PKG.PkgBuilder.BuildPkg(Int64 pfsSize)
   в LibOrbisPkg.PKG.PkgBuilder.Write(String filename, Action`1 logger)
   в PkgEditor.Views.GP4View.<>c__DisplayClass22_0.<buildPkg_Click>b__2()
   в System.Threading.Tasks.Task.Execute()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в PkgEditor.Views.GP4View.<buildPkg_Click>d__22.MoveNext()
   в LibOrbisPkg.PKG.PkgBuilder.BuildPkg(Int64 pfsSize)
   в LibOrbisPkg.PKG.PkgBuilder.Write(String filename, Action`1 logger)
   в PkgEditor.Views.GP4View.<>c__DisplayClass22_0.<buildPkg_Click>b__2()
   в System.Threading.Tasks.Task.Execute()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в PkgEditor.Views.GP4View.<buildPkg_Click>d__22.MoveNext()
```

**Comment by maxton** [comment] 2020-04-15 01:44
Can you upload a GP4 project that produces this error?

**Comment by nkrapivin** [comment] 2020-04-18 16:03
uh, it happens for me for every gp4 I create in Publishing Tools. o_O

**Comment by maxton** [comment] 2020-04-19 17:43
Ok, so can you upload one? If I can't reproduce this locally I can't fix it easily

**Comment by nkrapivin** [comment] 2020-04-20 12:54
https://drive.google.com/file/d/1rx0OJSOu_8b_sTfaqaIgCYBNk8nUPWvz/view?usp=sharing

have fun.

**Comment by tomazzz369z** [comment] 2020-04-20 22:39
same here, tested on project from post above on win xp and PkgTool-0.1.223

Preparing inner PFS...
 [innerpfs] Setting up filesystem structure...
 [innerpfs] Creating inodes (7 dirs and 70 files)...
 [innerpfs] Calculating data block layout...
Preparing outer PFS...
 [outerpfs] Setting up filesystem structure...
 [outerpfs] Creating inodes (0 dirs and 1 files)...
 [outerpfs] Calculating data block layout...
Preparing PKG header and body...

Unhandled Exception: System.Exception: Playgo Chunk hash file was not allocatedenough space. Report this as a bug
   at LibOrbisPkg.PKG.PkgBuilder.BuildPkg(Int64 pfsSize)
   at LibOrbisPkg.PKG.PkgBuilder.InitPkg()
   at LibOrbisPkg.PKG.PkgBuilder.Write(String filename, Action`1 logger)
   at PkgTool.Program.<>c.<.cctor>b__6_2(String[] args)
   at PkgTool.Verb.<>c__DisplayClass4_0.<Create>b__0(Dictionary`2 _, Dictionary`2 _2, String[] a)
   at PkgTool.Verb.Run(Verb[] verbs, String[] args, String name)
   at PkgTool.Program.Main(String[] args)

i can create this package only with PkgTool-0.1.221, all newer versions crash with error posted above

---

besides i noticed app does not support projects created by xvortex gengp4 - xml 1.1

Unhandled Exception: System.InvalidOperationException: There is an error in XML document (1, 16). ---> System.Xml.XmlException: Version number '1.1' is invalid. Line 1, position 16.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseXmlDeclaration(Boolean isTextDecl)
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Xml.XmlReader.MoveToContent()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderGp4Project.Read14_psproject()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(Stream stream)
   at LibOrbisPkg.GP4.Gp4Project.ReadFrom(Stream s)
   at PkgTool.Program.<>c.<.cctor>b__6_2(String[] args)
   at PkgTool.Verb.<>c__DisplayClass4_0.<Create>b__0(Dictionary`2 _, Dictionary`2 _2, String[] a)
   at PkgTool.Verb.Run(Verb[] verbs, String[] args, String name)
   at PkgTool.Program.Main(String[] args)

regards

**Comment by maxton** [comment] 2020-05-13 04:01
Ok, I can reproduce this but only on .NET Framework. I recommend you use .NET Core (PkgEditor.Core.exe) until the .NET Framework issue is found.

**Comment by maxton** [comment] 2020-05-14 17:45
This should be fixed now.

**Closed by maxton** 2020-05-14 17:45 UTC
